apiVersion: v1
kind: ConfigMap
metadata:
  name: small-store-config
  namespace: dev
data:
  DB_DRIVER: "org.postgresql.Driver"
  DB_URL: "jdbc:postgresql://postgres-db-service:5432/postgres"
  DB_USER: "admin"
  DB_PASS: "admin"
  POSTGRES_DB: "postgres"
  KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"
  KAFKA_BROKER_ID: "1"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  EUREKA_SERVICE_HOST: "eureka-service"
  EUREKA_SERVICE_PORT: "8761"
  EUREKA_USERNAME: "admin"
  EUREKA_PASSWORD: "admin"