spring:
  application:
    name: metric-server

server:
  port: 8889

logging:
  level:
    root: info

app:
  eureka:
    username: admin
    password: admin
    host: ${EUREKA_SERVICE_HOST:eureka-service}
    port: ${EUREKA_SERVICE_PORT:8761}
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@${app.eureka.host}:${app.eureka.port}/eureka/"
