apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        type: business
        app: api-gateway-service
    spec:
      containers:
      - image: e2rabi11/api-gateway-service:latest
        name: api-gateway-service
        ports:
        - containerPort: 8443
