apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        type: business
        app: api-gateway-service
    spec:
      containers:
      - image: e2rabi11/simple-store-api-gateway:latest
        name: api-gateway-service
        ports:
        - containerPort: 8443
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
          limits:
            memory: "250Mi"
            cpu: "1"
