apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        type: config
        app: config-server
    spec:
      priorityClassName: high-priority
      containers:
      - image: e2rabi11/simple-store-config-server:latest
        name: config-server
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
          limits:
            memory: "250Mi"
            cpu: "1"
