apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-edge-deployment
  namespace: dev
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: eureka-edge-server
  template:
    metadata:
      labels:
        type: config
        app: eureka-edge-server
    spec:
      priorityClassName: high-priority
      containers:
      - image: e2rabi11/simple-store-eureka-server:latest
        name: eureka-edge-server
        ports:
        - containerPort: 8761
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
          limits:
            memory: "250Mi"
            cpu: "1"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s