apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-server-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-server
  template:
    metadata:
      labels:
        type: config
        app: metric-server
    spec:
      containers:
      - image: e2rabi11/simple-store-metric-server:latest
        name: metric-server
        ports:
        - containerPort: 8889
