apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-server-deployment
  namespace: dev
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: metric-server
  template:
    metadata:
      labels:
        type: config
        app: metric-server
    spec:
      securityContext:
        runAsUser: 1000
      automountServiceAccountToken: false # Disable automating of default service account token
      containers:
      - image: e2rabi11/simple-store-metric-server:latest
        name: metric-server
        ports:
        - containerPort: 8889
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
          limits:
            memory: "250Mi"
            cpu: "1"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - valueFrom:
                configMapKeyRef:
                    name: small-store-config
                    key: EUREKA_SERVICE_HOST
            name: EUREKA_SERVICE_HOST
          - valueFrom:
                    configMapKeyRef:
                        name: small-store-config
                        key: EUREKA_SERVICE_PORT
            name: EUREKA_SERVICE_PORT