apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-composite-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-composite-service
  template:
    metadata:
      labels:
        app: product-composite-service
    spec:
      containers:
      - image: e2rabi11/simple-store-product-composite:latest
        name: product-composite-service
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
          limits:
            memory: "350Mi"
            cpu: "1"