apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service-deployment
  namespace: dev
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        type: business
        app: recommendation-service
    spec:
      containers:
      - image: e2rabi11/simple-store-recommendation:latest
        name: recommendation-service
        ports:
        - containerPort: 8083
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
          limits:
            memory: "250Mi"
            cpu: "1"
