apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service-deployment
  namespace: dev
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - image: e2rabi11/simple-store-review:latest
        name: review-service
        ports:
        - containerPort: 8083
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
        resources:
          requests:
            memory: "290Mi"
            cpu: "500m"
          limits:
            memory: "290Mi"
            cpu: "1"
