apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: small-store-db-pvc-volume
  namespace: staging
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi