
server:
  port: 8080

spring:
  application:
    name: recommendation-service
  datasource:
    url: jdbc:postgresql://postgres:5432/review?schema=recommendation
    username: review
    password: RVlCws5U0QTu
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    stream:
      bindings:
        deleteRecommendationConsumer-in-0:
          destination: product
          group: product-consumer-group
      kafka:
        binder:
          brokers: kafka
          consumer-properties:
            enable.auto.commit: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/