
server:
    port: 8002

spring:
  boot:
    admin:
      client:
        url: http://localhost:8889
  application:
    name: recommendation-service
  config:
    import: "configserver:"
  datasource:
    url: jdbc:postgresql://ep-curly-thunder-a5bovt5y.us-east-2.aws.neon.tech:5432/review?schema=recommendation
    username: review
    password: RVlCws5U0QTu
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    stream:
      bindings:
        deleteRecommendationConsumer-in-0:
          destination: recommendation
          group: recommendation-consumer-group
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            enable.auto.commit: false
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
        max-attempts: 20
      uri: http://localhost:8888
      enabled: true
      username: admin
      password: admin
app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@127.0.0.1:8761/eureka/"
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true