apiVersion: v1
kind: Secret
metadata:
  namespace: staging
  name: small-store-secret
type: kubernetes.io/opaque
data:
  review-db-username: cmV2aWV3
  review-db-password: UlZsQ3dzNVUwUVR1
  recommendation-db-username: cmV2aWV3
  recommendation-db-password: UlZsQ3dzNVUwUVR1