server:
  port: 8001

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://ep-curly-thunder-a5bovt5y.us-east-2.aws.neon.tech:5432/review
    username: review
    password: RVlCws5U0QTu
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true