spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  boot:
    admin:
      client:
        url: "http://${METRIC_SERVICE_SERVICE_HOST}:${METRIC_SERVICE_SERVICE_PORT}"
        instance:
          service-base-url: "http://${REVIEW-SERVICE_SERVICE_HOST}:${REVIEW-SERVICE_SERVICE_PORT}"
          metadata:
            name: review-service-k8s
  application:
    name: review-service-k8s
  config:
    activate:
      on-profile: k8s
    import: "configserver:"
  cloud:
    loadbalancer:
      enabled: false
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
        max-attempts: 20
      uri: http://config-service:8888
      enabled: true
      username: admin
      password: admin