apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
    name: ayoub
    namespace: dev
spec:
    request: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZZWGx2ZFdJd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFDeDVJNkx4dTBFK1pNMmpaMXFmSC9KcHpwdG5oclY1N2pYUTlKMG9QRmNQK01vCnlqN0YrdHcwZkFRY25qejF6c2pYT3BPNUc3NlhQaldXbHd2RGtJQ0RtamtYSG5DQlppNEpQQWN1QXdGWnQwR0kKWlNrNEovdjMvdW52SGZMT1NJT0grdHhMbUxBcVFXWGo4OHNXOGoxVDg1aHd0WGNsNXdlT0xaekRleUpZclphbwpPYWFrQXl1UGNXK0J1Vno0L1EweEVvdzlpSWF1cUtuZ3ZZdjFmVXQrZmdxYlkwRVN4WHJrNmx4TlZxMlBiNEVWCkNxbUx0L2V5SXRJU3RlTXM4YU5XWjFPc1k5cmcra1dlMitSc2g0QmNhc2g1TFc4UWxsV2hOQWkvN1hZclByeUMKWm1XcURMaUV5NzQwTllCUkowdEl6eTF0MWlDS0pRQUxMWmhEMkk0QkFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFleVZiby93VExQbkV0azFTa0g3eTJIRTJiclkxSDB2MW1PK09hYjBCUFhKaVRqdnZWbXVQCmJCUy90bXI1RkptUExDTmY0VEYyTDVIWFFQVGhHWGVtREl5eGVSZkhrZWFwZ25XKzRMd2RBbGQvZkRPRjRNNjAKNVpmUUx5WlZmSlZMVVhQMTJKZklKSnVtUkd6WVg3M3VqdEY5eklEeVNTcWlwN2pBQ3NxMVdkNXRWVG15WVpKbApKN0l5T1RWbmwzT0JtVlhaRXlsY2RNNDFkRUZ3bUFlYlBaQ3kvNHpWWW8rWlV5UHJhOEprbndQT2xmUFJ4M1hjCnBuRnUweEMyenUxSTBXVy9JMnpLY0NqQU9GVG94VndvUFh2Vlh5QjN2aEY3cXVYdXAvdXdYbzdhY0ZVL2hjMHYKUmNMNWMvbUhvWWkwZHpzVTlONGZsWXJrUjBpS1lxZ1lsZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo="
    signerName: kubernetes.io/kube-apiserver-client
    usages:
        - digital signature
        - key encipherment
        - client auth
    expirationSeconds: 31536000  # 1 year