apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: dev
spec:
  selector:
    app: small-store-tiers-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017