apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: dev
spec:
  selector:
    app: small-store-tiers-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432