apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081