apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082