server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost

spring:
  boot:
    admin:
      client:
        url: http://localhost:8889
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: "configserver:"
  cloud:
    config:
        fail-fast: true
        retry:
          initial-interval: 3000
          multiplier: 1.3
          max-interval: 10000
          max-attempts: 20
        uri: http://localhost:8888
        username: admin
        password: admin
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-composite
          uri: lb://product-composite
          predicates:
            - Path=/v1/product-composite/**
        - id: product-composite-swagger
          uri: lb://product-composite
          predicates:
            - Path=/openapi/**
        - id: eureka-web-start
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-web-others
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: config-server
          uri: http://localhost:8888
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*),/$\{segment}
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@localhost:8761/eureka/"
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: debug
    org.springframework.cloud.gateway: debug