
server:
  port: 8000

spring:
  application:
    name: api-gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true