server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-composite
          uri: lb://product-composite-service
          predicates:
            - Path=/v1/product-composite/**
        - id: product-composite-swagger
          uri: lb://product-composite-service
          predicates:
            - Path=/openapi/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/