spring:
  config:
    import: "configserver:"
  application:
    name: api-gateway
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
        max-attempts: 20
      uri: http://config-server:8888
app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@eureka:8761/eureka/