server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-composite
          uri: lb://product-composite-service
          predicates:
            - Path=/v1/product-composite/**
        - id: product-composite-swagger
          uri: lb://product-composite-service
          predicates:
            - Path=/openapi/**

app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@eureka:8761/eureka/