server:
  port: 8081
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  boot:
    admin:
      client:
        url: "http://${METRIC_SERVICE_SERVICE_HOST}:${METRIC_SERVICE_SERVICE_PORT}"
        instance:
          service-base-url: "http://${REVIEW-SERVICE_SERVICE_HOST}:${REVIEW-SERVICE_SERVICE_PORT}"
          metadata:
            name: product-service
  application:
    name: product-service-k8s
  data:
    mongodb:
      host: ${MONGODB_SERVICE_SERVICE_HOST}
      port: ${MONGODB_SERVICE_SERVICE_PORT}
      database: product-db
  config:
    activate:
      on-profile: k8s
  cloud:
    config:
      enabled: false
    loadbalancer:
      enabled: false
    stream:
      bindings:
        deleteProductConsumer-in-0:
          destination: product
          group: product-consumer-group
      kafka:
        binder:
          brokers: "${KAFKA_SERVICE_SERVICE_HOST}:${KAFKA_SERVICE_SERVICE_PORT}"
          consumer-properties:
            enable.auto.commit: false
app:
  eureka:
    username: ${EUREKA_USERNAME}
    password: ${EUREKA_PASSWORD}
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@${EUREKA_SERVICE_SERVICE_HOST}:8761/eureka/"
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_SERVICE_SERVICE_HOST}:${ZIPKIN_SERVICE_SERVICE_PORT}/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "*"