server:
  port: 8009

spring:
  data:
   mongodb:
      host: 127.0.0.1
      port: 27017
      database: product-db
  cloud:
    stream:
      bindings:
        deleteProductConsumer-in-0:
          destination: product
          group: product-consumer-group
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            enable.auto.commit: false

