server:
  port: 8009

spring:
  application:
    name: PRODUCT-SERVICE
  data:
   mongodb:
      host: 127.0.0.1
      port: 27017
      database: product-db
  cloud:
    stream:
      bindings:
        deleteProductConsumer-in-0:
          destination: product
          group: product-consumer-group
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            enable.auto.commit: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
