apiVersion: v1
kind: LimitRange
metadata:
  name: memory-cpu-resource-constraints
  namespace: dev
spec:
    limits:
      - default:
          cpu: "500m"
          memory: "280Mi"
        defaultRequest:
          cpu: "500m"
          memory: "250Mi"
        max:
            cpu: "1"
            memory: "500Mi"
        min:
            cpu: "100m"
            memory: "100Mi"
        type: Container