apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quotas
  namespace: dev
spec:
    hard:
        requests.cpu: "6"
        requests.memory: "2Gi"
        limits.cpu: "4"
        limits.memory: "2Gi"
        pods: "10"
        services: "5"
        configmaps: "10"
        secrets: "10"